import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 's',
};

export default function Head() {
  return (
    <>
      <title>FinovaTrack</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      {/* <script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-L8G3KWJZDF"
      />
      <script
        dangerouslySetInnerHTML={{
          __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-L8G3KWJZDF')
              `,
        }}
      /> */}
    </>
  );
}
