// Dados fakes para financialPlanningYear

import { IFinancialPlanningProps } from "./getFinancialPlanningYear";

export const fakeFinancialPlanningYear: IFinancialPlanningProps[] = [
  {
    id: '4',
    year: '2024',
    investments: '2500',
    reserve: '150',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  },
  {
    id: '5',
    year: '2025',
    investments: '3000',
    reserve: '200',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  },
  {
    id: '6',
    year: '2026',
    investments: '3500',
    reserve: '250',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  },
  {
    id: '7',
    year: '2027',
    investments: '4000',
    reserve: '300',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  },
  {
    id: '8',
    year: '2028',
    investments: '4500',
    reserve: '350',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  },
  {
    id: '9',
    year: '2029',
    investments: '5000',
    reserve: '400',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  },
  {
    id: '10',
    year: '2030',
    investments: '5500',
    reserve: '450',
    monthlyContributions: '500',
    receivables: '0',
    deduction: '0',
    periodContributions: '12',
    totoalReserveLastYear: '',
  }
]
