export const tickerToCompanyName: any = {
  MSFT_US_EQ: 'Microsoft Corporation',
  AAPL_US_EQ: 'Apple',
  O_US_EQ: 'Realty Income Corporation',
  JNJ_US_EQ: 'Johnson & Johnson',
  CNQ_US_EQ: 'Canadian Natural Resources Limited',
  KO_US_EQ: 'Coca-Cola',
  PEP_US_EQ: 'PepsiCo',
  MA_US_EQ: 'Mastercard Incorporated',
  PG_US_EQ: 'Procter & Gamble',
  LTC_US_EQ: 'LTC Properties',
  MCD_US_EQ: "McDonald's Corporation",
  JPM_US_EQ: 'JPMorgan Chase',
  IBM_US_EQ: 'International Business Machines Corporation',
  CAH_US_EQ: 'Cardinal Health',
  BMY_US_EQ: 'Bristol-Myers Squibb',
  GD_US_EQ: 'General Dynamics Corporation',
  RY_US_EQ: 'Royal Bank of Canada',
  BMO_US_EQ: 'Bank of Montreal',
  BNS_US_EQ: 'Bank of Nova Scotia',
  CB_US_EQ: 'Chubb Limited',
  LOW_US_EQ: "Lowe's Companies",
  SYY_US_EQ: 'Sysco Corporation',
  ITW_US_EQ: 'Illinois Tool Works',
  WMT_US_EQ: 'Walmart',
  KMB_US_EQ: 'Kimberly-Clark Corporation',
  MAIN_US_EQ: 'Main Street Capital Corporation',
  BLK_US_EQ: 'BlackRock',
  ADP_US_EQ: 'Automatic Data Processing',
  SBUX_US_EQ: 'Starbucks Corporation',
  CSCO_US_EQ: 'Cisco Systems',
  ECL_US_EQ: 'Ecolab',
  CVX_US_EQ: 'Chevron Corporation',
  PSEC_US_EQ: 'Prospect Capital Corporation',
  AGNC_US_EQ: 'AGNC Investment',
  STAG_US_EQ: 'STAG Industrial',
  AFL_US_EQ: 'Aflac Incorporated',
  PPG_US_EQ: 'PPG Industries',
  GOOD_US_EQ: 'Gladstone Commercial Corporation',
  NUE_US_EQ: 'Nucor Corporation',
  EMR_US_EQ: 'Emerson Electric',
  ADM_US_EQ: 'Archer-Daniels-Midland',
  PNR_US_EQ: 'Pentair plc',
  TROW_US_EQ: 'T. Rowe Price Group',
  BEN_US_EQ: 'Franklin Resources',
  TD_US_EQ: 'Toronto-Dominion Bank',
  SHW_US_EQ: 'Sherwin-Williams',
  SLB_US_EQ: 'Schlumberger Limited',
  GWW_US_EQ: 'W.W. Grainger',
  ADC_US_EQ: 'Agree Realty Corporation',
  ROP_US_EQ: 'Roper Technologies',
  LHAd_EQ: 'Deutsche Lufthansa'
}
